parameters:
    markup_oembed.cache_key_delimiter.default: ':'

services:
    Markup\OEmbedBundle\Service\OEmbedService:
        arguments:
            $client: '@Markup\OEmbedBundle\Client\GuzzleClient'
            $providerLocator: '@markup_oembed.provider_locator'
            $cacheKeyDelimiter: '%markup_oembed.cache_key_delimiter%'
        autowire: true
    markup_oembed: '@Markup\OEmbedBundle\Service\OEmbedService'
    Markup\OEmbedBundle\Client\GuzzleClient:
        public: false
    Markup\OEmbedBundle\Twig\Extension:
        arguments:
            $shouldSquashRenderingErrors: '%markup_oembed.squash_rendering_errors%'
        autowire: true
        tags:
            - { name: twig.extension }
    Markup\OEmbedBundle\Serializer\OEmbedSerializer:
        public: false

    Markup\OEmbedBundle\Cache\ObjectCache:
        arguments:
            - '@markup_oembed.string_cache'
            - '@Markup\OEmbedBundle\Serializer\OEmbedSerializer'
        public: false

    markup_oembed.provider_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments: [[]]
        public: false

    Markup\OEmbedBundle\Console\:
        resource: '../../Console/*'
        autowire: true
        autoconfigure: true
