parameters:
    markup_oembed.cache_key_delimiter.default: ':'

services:
    markup_oembed:
        class: 'Markup\OEmbedBundle\Service\OEmbedService'
        arguments:
            - '@markup_oembed.client'
            - '@markup_oembed.provider_factory'
            - '@markup_oembed.object_cache'
            - '%markup_oembed.cache_key_delimiter%'
    markup_oembed.provider_factory:
        class: Markup\OEmbedBundle\Provider\ProviderFactory
        arguments:
            - '@service_container'
            - 'markup_oembed.provider'
        public: false
    markup_oembed.client.guzzle:
        class: 'Markup\OEmbedBundle\Client\GuzzleClient'
        public: false
    markup_oembed.client:
        alias: markup_oembed.client.guzzle
    markup_oembed.twig.extension:
        class: 'Markup\OEmbedBundle\Twig\Extension'
        arguments:
            - '@markup_oembed'
            - '%markup_oembed.squash_rendering_errors%'
        tags:
            - { name: twig.extension }
    markup_oembed.serializer:
        class: 'Markup\OEmbedBundle\Serializer\OEmbedSerializer'
        public: false

    markup_oembed.object_cache:
        class: 'Markup\OEmbedBundle\Cache\ObjectCache'
        arguments:
            - '@markup_oembed.string_cache'
            - '@markup_oembed.serializer'
        public: false
