language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.1
          env: deps=low

env:
    global:
        - deps=high

before_script:
    - if [ "$deps" = "high" ]; then composer install --dev --prefer-source; fi;
    - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable --ignore-platform-reqs update; fi
    - if [ -f $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini ]; then phpenv config-rm xdebug.ini; fi

script:
    - vendor/bin/phpunit -v
    - vendor/bin/phpstan analyse . --level 8

dist: xenial

notifications:
  email: "douglas@usemarkup.com"
