language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script: composer install --dev --prefer-source

script:
    - vendor/bin/phpunit -v

dist: trusty
sudo: required

notifications:
  email: "douglas@usemarkup.com"
