language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script: composer install --dev --prefer-source

script:
    - vendor/bin/phpunit -v
    - vendor/bin/phpstan analyse . --level 8

dist: xenial

notifications:
  email: "douglas@usemarkup.com"
