language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        php: nightly

before_script: composer install --dev --prefer-source

script:
    - vendor/bin/phpunit -v

dist: trusty

notifications:
  email: "douglas@usemarkup.com"
